name: CI
on:
  push:
    branches: [ main ]
 
  workflow_dispatch:
jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        version: 12
    - name: GitHub Action for Yarn
 
    uses: Borales/actions-yarn@v2.1.0
    with:
    
    cmd: install
    -name: creating build
    run: yarn build

    -name: installing Surge
    run: npm install -g surge
    
    -name: deploying
    run: surge ./build http://liaqat2.surge.sh/ --token ${{secrets:A}}